### ISSUE TITLE
James Fenn

### ISSUE THREAD

**Issue by alexandrepiveteau** [DoubleDotLabs/Letters#1]
> James Fenn is an issue.

**Comment by PDDStudio** [comment]
This is a known bug since I know James

**Comment by adueppen** [comment]
Can confirm.

**Comment by DarinMenezes** [comment]
It's a big issue. Everytime I open the app I notice this and have to force stop and uninstall it : (

**Comment by fennifith** [comment]
![im_ded](https://cloud.githubusercontent.com/assets/13000407/15807244/b6cba008-2b26-11e6-945a-cb9e3b34368f.png)
